# Copyright (c) 2021 Peptone.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# BERT Pretraining from Preprocessed (tokenized) data
name: &name InferenceBERTFromPreprocessed
trainer:
  gpus: 1 # the number of gpus, 0 for CPU, or list with gpu indices
  num_nodes: 1
  precision: 16 # 16 to use AMP
  fast_dev_run: False
  checkpoint_callback: false # provided by exp_manager
  logger: false # provided by exp_manager

model:
  nemo_path: 'bert_base_proteonemo.nemo' # exported .nemo path
  representations_path: 'bert_reprs'

  language_model:
    pretrained_model_name: bert-base-uncased # huggingface model name
    lm_checkpoint: null
    config:
      attention_probs_dropout_prob: 0.1
      hidden_act: gelu
      hidden_dropout_prob: 0.1
      hidden_size: 768
      initializer_range: 0.02
      intermediate_size: 3072
      max_position_embeddings: 1024
      num_attention_heads: 12
      num_hidden_layers: 12
      type_vocab_size: 2
      vocab_size: 30522
    config_file: null # json file, precedence over config

  tokenizer: null

  infer_ds:
    data_file: '/data/UNIREF50/hdf5_seq_len_1024_max_pred_160_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5/uniref_50/uniref50_en_training_0.hdf5' # path to hdf5 file (or directory)
    max_predictions_per_seq: 160
    batch_size: 16
    shuffle: false
    num_samples: -1
    num_workers: 8
    drop_last: false
    pin_memory: false

exp_manager:
  exp_dir: null # where to store logs and checkpoints
  name: *name # name of experimentvim
  create_tensorboard_logger: True
  create_checkpoint_callback: True


hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null
